# Generated by Django 2.1.4 on 2018-12-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_chapter_chapter_id'),
        ('users', '0002_auto_20181225_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='host',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
