# Generated by Django 2.1.4 on 2018-12-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='host',
            new_name='book',
        ),
    ]
