# Generated by Django 2.1.4 on 2018-12-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bookcapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.CharField(blank=True, max_length=100)),
                ('word_size', models.CharField(blank=True, max_length=100)),
                ('bg_color', models.CharField(blank=True, max_length=100)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
