# Generated by Django 2.1.4 on 2018-12-21 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181220_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_time',
        ),
    ]
