# Generated by Django 2.1.4 on 2018-12-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_abstract',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
