# Generated by Django 2.1.4 on 2018-12-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_book_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_id',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
